### ISSUE TITLE
How to define a nested property?

### ISSUE THREAD

**Issue by AntoninSlejska** [leonardomso/graphql-mongodb-server#12]
I want to save in the database posts, that have a nested property, like this:

```
const post = {
  title: 'some title',
  body: 'some text',
  date: {
    published: '2019-06-28T10:00:00',
    updated: '2019-06-29T11:00:00'
  }
}
```

I try it like this:

**1. /server/models/posts**

```
const PostSchema = new Schema({
  title: {
    type: String,
    required: true
  },
  body: {
    type: String,
    required: true
  },
  date: {
    published: {
      type: Date,
      default: Date.now()
    },
    updated: {
      type: Date,
      default: Date.now()
    }
  }
});
```

**2. /graphql/types/Post/index.js**

```
export default `
  type Dates {
    published: String
    updated: String
  }

  type Post {
    _id: ID!
    title: String!
    body: String!
    date: Dates
  }

  type Query {
    post(_id: ID!): Post!
    posts: [Post!]!
  }

  type Mutation {
    createPost(post: CreatePostInput): Post!
    updatePost(_id: ID!, post: UpdatePostInput): Post!
    deletePost(_id: ID!): Post!
  }

  type Subscription {
    post: PostSubscriptionPayload!
  }

  type PostSubscriptionPayload {
    mutation: MutationType!
    post: Post!
  }

  input CreatePostInput {
    title: String!
    body: String!
    date: Dates
  }
  
  input UpdatePostInput {
    title: String
    body: String
    date: Dates
  }

  enum MutationType {
    CREATED
    DELETED
    UPDATED
  }
`;
```

**3. /graphql/resolvers/Post/index.js**

```
import Post from "../../../server/models/Post";

export default {
  Query: {
    post: async (parent, { _id }, context, info) => {
      return await Post.findOne({ _id }).exec();
    },
    posts: async (parent, args, context, info) => {
      const res = await Post.find({})
        .populate()
        .exec();

      return res.map(u => ({
        _id: u._id.toString(),
        title: u.title,
        body: u.body,
        date: u.date
      }));
    }
  },
  Mutation: {
    createPost: async (parent, { post }, context, info) => {
      const newPost = await new Post({
        title: post.title,
        body: post.body,
        date: post.date
      });
      try {
        const result = await new Promise((resolve, reject) => {
         newPost.save((err, res) => {
            err ? reject(err) : resolve(res);
          });
        });

        return newPost;
      } catch (error) {
        console.log(error);
        throw error;
      }
    },
    updatePost: async (parent, { _id, post }, context, info) => {
      return new Promise((resolve, reject) => {
        Post.findByIdAndUpdate(_id, { $set: { ...post } }, { new: true }).exec(
          (err, res) => {
            err ? reject(err) : resolve(res);
          }
        );
      });
    },
    deletePost: async (parent, { _id }, context, info) => {
      try {
        // searching for creator of the post and deleting it from the list
        const post = await Post.findById(_id);
        return new Promise((resolve, reject) => {
          Post.findByIdAndDelete(_id).exec((err, res) => {
            err ? reject(err) : resolve(res);
          });
        });
      } catch (error) {
        console.log(error);
        throw error;
      }
    }
  },
  Subscription: {
    post: {
      subscribe: (parent, args, { pubsub }) => {
        //return pubsub.asyncIterator(channel)
      }
    }
  },
  Post: {
  }
};
```

When I test the createPost mutation, then I get the following error message:

> The type of UpdatePostInput.date must be Input Type but got: Dates.
>     at assertValidSchema (C:\Workspace\Sites\react\graphql\node_modules\graphql\type\validate.js:71:11)
>     at Object.validate (C:\Workspace\Sites\react\graphql\node_modules\graphql\validation\validate.js:55:35)
>     at doRunQuery (C:\Workspace\Sites\react\graphql\node_modules\apollo-server-core\src\runQuery.ts:181:30)
>     at C:\Workspace\Sites\react\graphql\node_modules\apollo-server-core\src\runQuery.ts:80:39
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Error: The type of CreatePostInput.date must be Input Type but got: Dates.

**Comment by leonardomso** [comment]
I think that the errors are that instead of creating an _Input_ type for _Dates_, you created a _Type_, that's why it's throwing you this error.

**Comment by AntoninSlejska** [comment]
The correct **/graphql/types/Post/index.js** should look like:

```
export default `
  type Dates {
    published: String
    updated: String
  }

  type Post {
    _id: ID!
    title: String!
    body: String!
    date: Dates
  }

  type Query {
    post(_id: ID!): Post!
    posts: [Post!]!
  }

  type Mutation {
    createPost(post: CreatePostInput): Post!
    updatePost(_id: ID!, post: UpdatePostInput): Post!
    deletePost(_id: ID!): Post!
  }

  type Subscription {
    post: PostSubscriptionPayload!
  }

  type PostSubscriptionPayload {
    mutation: MutationType!
    post: Post!
  }
  
  input DatesInput {
    published: String
    updated: String
  }

  input CreatePostInput {
    title: String!
    body: String!
    date: DatesInput
  }
  
  input UpdatePostInput {
    title: String
    body: String
    date: DatesInput
  }

  enum MutationType {
    CREATED
    DELETED
    UPDATED
  }
`;
```

**Comment by leonardomso** [comment]
@AntoninSlejska please open a PR so we can fix it! I'll merge it right away!

**Comment by AntoninSlejska** [comment]
I have prepared the PR: https://github.com/leonardomso/graphql-mongodb-server/pull/15

Thanks!
